/**
 * Finding the same element again in a page fetched later.
 *
 * This is the hard part of the product. Glasswing needs a selector that works
 * for the next few seconds in the page it just read; a watch needs one that
 * still resolves next Tuesday, in HTML the site has rebuilt in the meantime.
 *
 * So the rules here are about durability, not brevity. An id generated by a
 * framework is worse than useless: it looks like the most stable thing on the
 * page and changes on every deploy.
 */

/**
 * Whether an identifier was written by a person or produced by a build.
 *
 * The tells are consistent across frameworks: React's useId (":r3:"), Emotion
 * and CSS modules (a hash suffix), Ember and Angular counters, and anything
 * that is mostly digits or mostly consonants.
 */
export function looksGenerated(value: string): boolean {
  const name = value.trim();
  if (!name) return true;

  if (name.includes(':')) return true; // React useId
  if (/^(ember|ng-|mat-|radix-|headlessui-|react-aria-|downshift-)/i.test(name)) return true;
  if (/^(css|sc|emotion|jss)-[a-z0-9]{4,}$/i.test(name)) return true; // styled-components, Emotion
  if (/__[a-z0-9]{5,}$/i.test(name)) return true; // CSS modules: Button_root__x8f2k
  if (/[0-9a-f]{8,}/i.test(name)) return true; // any embedded hash
  if (/\d{4,}/.test(name)) return true; // a long counter
  if (/^[a-z]{1,2}\d+$/i.test(name)) return true; // e2, x17

  // Mostly digits is a counter wearing a word as a hat.
  const digits = (name.match(/\d/g) ?? []).length;
  return digits > 0 && digits / name.length > 0.4;
}

/**
 * Whether a class name says what something is.
 *
 * Utility classes describe how a thing looks, and a redesign rewrites every
 * one of them. "price" survives a redesign; "text-sm" does not, and there are
 * forty of them on the element anyway.
 */
export function isSemanticClass(value: string): boolean {
  const name = value.trim();
  if (!name || looksGenerated(name)) return false;
  if (name.length < 3 || name.length > 32) return false;

  // Tailwind and friends: a leading utility prefix, a breakpoint, or a state.
  if (/^(sm|md|lg|xl|2xl|hover|focus|active|group|dark|print):/.test(name)) return false;
  if (
    /^(t|b|l|r|x|y|p|m|w|h|z|gap|flex|grid|text|bg|border|rounded|shadow|opacity|order|col|row|space|inset|top|left|right|bottom|font|leading|tracking|items|justify|self|object|overflow|cursor|select|transition|duration|ease|delay|scale|rotate|translate|min|max|basis|grow|shrink|pt|pb|pl|pr|px|py|mt|mb|ml|mr|mx|my)-/.test(
      name
    )
  ) {
    return false;
  }
  return true;
}

/** Attributes put on an element specifically so it can be found again. */
const ANCHOR_ATTRIBUTES = ['data-testid', 'data-test-id', 'data-test', 'data-cy', 'itemprop'];

function anchorAttribute(el: Element): string | null {
  for (const name of ANCHOR_ATTRIBUTES) {
    const value = el.getAttribute(name);
    if (value && !looksGenerated(value)) return `[${name}="${escapeValue(value)}"]`;
  }
  return null;
}

function escapeValue(value: string): string {
  return value.replace(/["\\]/g, '\\$&');
}

/** One step of the path: the tag, plus whatever makes it distinguishable. */
function step(el: Element): string {
  const tag = el.tagName.toLowerCase();

  const semantic = [...el.classList].filter(isSemanticClass).slice(0, 2);
  let part = tag + semantic.map((c) => `.${CSS_escape(c)}`).join('');

  const parent = el.parentElement;
  if (!parent) return part;

  // Only add a position when the selector so far does not already single the
  // element out. A position is the most fragile thing here: it breaks the
  // moment the site inserts a row above.
  const siblings = [...parent.children].filter((sibling) => matchesLoose(sibling, tag, semantic));
  if (siblings.length > 1) part += `:nth-of-type(${indexAmongType(el) + 1})`;
  return part;
}

function matchesLoose(el: Element, tag: string, classes: string[]): boolean {
  if (el.tagName.toLowerCase() !== tag) return false;
  return classes.every((c) => el.classList.contains(c));
}

function indexAmongType(el: Element): number {
  const parent = el.parentElement;
  if (!parent) return 0;
  return [...parent.children].filter((c) => c.tagName === el.tagName).indexOf(el);
}

/** CSS.escape is not in every context this runs in, and the need is narrow. */
function CSS_escape(value: string): string {
  return value.replace(/([^a-zA-Z0-9_-])/g, '\\$1');
}

/**
 * A selector for an element, built to survive the page being rebuilt.
 *
 * Tried in order of how long each kind of anchor tends to last: an id a person
 * wrote, an attribute put there to be selected by, then the shortest path of
 * meaningful ancestors. The path stops at the first ancestor that is itself
 * anchored, which keeps it short and stops a change in the page header from
 * breaking a watch on the footer.
 */
export function stableSelector(el: Element): string {
  const id = el.getAttribute('id');
  if (id && !looksGenerated(id)) return `#${CSS_escape(id)}`;

  const anchor = anchorAttribute(el);
  if (anchor) return anchor;

  const parts: string[] = [];
  let node: Element | null = el;
  let depth = 0;

  while (node && node.tagName !== 'HTML' && depth < 6) {
    const nodeId = node.getAttribute('id');
    if (node !== el && nodeId && !looksGenerated(nodeId)) {
      parts.unshift(`#${CSS_escape(nodeId)}`);
      return parts.join(' > ');
    }

    const nodeAnchor = node !== el ? anchorAttribute(node) : null;
    if (nodeAnchor) {
      parts.unshift(nodeAnchor);
      return parts.join(' > ');
    }

    parts.unshift(step(node));
    node = node.parentElement;
    depth++;
  }

  return parts.join(' > ');
}

/**
 * How much to trust a selector, before the user commits to it.
 *
 * Shown when a watch is created, because the honest moment to say "this may
 * not survive a redesign" is then, not in a notification that never arrives.
 */
export type Confidence = 'high' | 'medium' | 'low';

export function confidenceOf(selector: string): Confidence {
  if (/^#/.test(selector) || /^\[data-/.test(selector)) return 'high';
  if (selector.includes(':nth-of-type')) return 'low';
  return 'medium';
}

export function confidenceNote(confidence: Confidence): string {
  if (confidence === 'high')
    return 'This element has a stable id, so the watch should survive a redesign.';
  if (confidence === 'medium')
    return 'Found by its position in the page structure. A redesign could move it.';
  return 'Found by counting position among similar elements. If the page reorders, this watch may need setting up again.';
}
